image: python:3.9

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - make test
      - step:
          name: Coverage
          script:
            - if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - make coverage
